language: c
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386


script:
- if [[ ${TRAVIS_BRANCH} == "source" ]]; then make deploy; fi

env:
  global:
    secure: i5fkTwWAltTEmXLiOkBMgfk7O38kCiIEAWXDhW2yWhPdzpN1mm9PQ56sohKUumhgSAotx78gO8vwHOvjZ5d/qd6Xy5jbtrGd23CCDdF1XxtcWZeVVVP9o0mdqkFzeLwi6Qt0KdvoEkGdXuBebc97tyVtDnmcKC5z9HyR7TvWam5OLrCcN7iFepDjrPpiTyo3z7hjRArwZ6C1lZ4QxwnacRx4yEG43MdX1WSRwZ1StRumxGqyKvZwBWubrswRzrhGFJcEuJTaoO51fnCNhIR2I5TDAx/ee6o3LeCbT6eYtQllQScCC6TuPXKlf8daI3yYi/RzXBWdrZChiLCBAj1uygQq0sLWshY4km0rSXI5bKIuijBg3eAAZnEtv1WHsKs09tqzo8RBu4q7yWTaZSkv5/ZWc3R6fG1/4wvdTQrhMcnmmGD9K3eWD0RoddRJEiGXxD/39SzrtZlv22M6oLBw89gvi+dcLJ11iTM1r8e5ue8aXBpapPX9eeJvtkdr5bU0ZJJG91JPGD61FaQAkORQfe0gz2Zl3/AwIh6NI9vgbjoL8bY25/sXMH36Uq5XlJdFNRBgen/phUDaSBrFnt5Qhl2At45uwnA8X7lOeHCgWbMQh9QDkDrDGEd4vEVpIIlg6A7ppjXQGI/BGbwFoAErVfmFnG7fY8PmQTa7FjsalIM=
